import Head from "next/head";
import { trpc } from "../utils/trpc";

export default function Home() {
  const result = trpc.greeting.useQuery({ name: "zahid" });

  if (!result.data) {
    return <div>Loading...</div>;
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{result.data.text}</h1>
      </main>
    </div>
  );
}
